### ISSUE TITLE
netscaler_lb_vserver: nitro exception errorcode=1092

### ISSUE THREAD

**Issue by cwegener** [citrix/netscaler-ansible-modules#4]
Netscaler version:
```
NetScaler NS11.1: Build 50.10.nc, Date: Nov  6 2016, 05:42:29
```

Ansible task from playbook:
```
    - name: LB vServer
      delegate_to: localhost
      connection: local
      netscaler_lb_vserver:
        nsip: "{{ ctx_ns_nsip }}"
        nitro_user: "{{ ctx_ns_nitro_user }}"
        nitro_pass: "{{ ctx_ns_nitro_pass }}"
        comment: Managed by Ansible
        ipv46: 10.30.3.176
        lbmethod: LRTM
        name: "lb_vs_http_ctx_sf_80"
        persistencetype: SOURCEIP
        port: 80
        servicetype: HTTP
        servicebindings:
          - servicename: svc_http_LAB3TST3_80
```

Tail of ansible output:
```
    "loglines": [
        "Applying actions for state present",
        "Checking if lb vserver exists",
        "Add lb vserver"
    ],
    "msg": "nitro exception errorcode=1092, message=Arguments cannot both be specified [RecursionAvailable, serviceType==HTTP]"
```

I'll try a firmware update to the latest 11.1 to see if it fixes the error.
