### ISSUE TITLE
Reproducible error when adding servers with ipaddresses

### ISSUE THREAD

**Issue by mikeycmccarthy** [citrix/netscaler-ansible-modules#48]
I'm running a task to add servers like this:
```
- hosts: netscaler_frontend_hosts
  gather_facts: no
  tasks:

  - name: Collect network information
    setup:
      gather_subset: '!all,!min,network'

  - name: Register servers
    delegate_to: localhost
    netscaler_server:
      nsip: "{{ ip }}"
      validate_certs: "{{ validate_certs }}"
      nitro_user: "{{ user }}"
      nitro_pass: "{{ password }}"
      state: present
      ipaddress: "{{ ansible_default_ipv4.address }}"
      name: "{{ ansible_hostname }}"
```

I've noticed that if I trash these servers in the UI I can consistently get a fatal error when adding one of these servers:

```
TASK [Collect network information] ************************************************************************************************************************************************************************************************************************************************************************************
Thursday 26 April 2018  16:01:06 +0100 (0:00:00.066)       0:00:00.066 ********
ok: [michael1]
ok: [michael2]

TASK [Register servers] ***********************************************************************************************************************************************************************************************************************************************************************************************
Thursday 26 April 2018  16:01:08 +0100 (0:00:01.720)       0:00:01.786 ********
fatal: [michael1 -> localhost]: FAILED! => {"changed": false, "loglines": ["Applying actions for state present", "Checking if server exists"], "msg": "nitro exception errorcode=293, message=Operation already in progress"}
changed: [michael2 -> localhost] => {"changed": true, "loglines": ["Applying actions for state present", "Checking if server exists", "Enabling server", "Sanity checks for state present", "Checking if server exists", "Checking if configured server is identical"]}
```

If I look in the UI then both servers are created just fine, so I think its a misleading error message.

Do you know what might be causing this?

ansible 2.5.1
python version = 2.7.14 (default, Mar 22 2018, 14:43:05) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
module installed from trunk to get https://github.com/citrix/netscaler-ansible-modules/issues/45
