### ISSUE TITLE
not able to assign monitor to service or service_group

### ISSUE THREAD

**Issue by aelrayess** [citrix/netscaler-ansible-modules#6]
whenever i try to assign a monitor to a service or a service group i get the below message

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_y8i6dE/ansible_module_netscaler_servicegroup.py", line 974, in <module>
    main()
  File "/tmp/ansible_y8i6dE/ansible_module_netscaler_servicegroup.py", line 922, in main
    if not monitor_bindings_identical(client, module):
  File "/tmp/ansible_y8i6dE/ansible_module_netscaler_servicegroup.py", line 587, in monitor_bindings_identical
    configured_bindings = get_configured_monitor_bindings(client, module)
  File "/tmp/ansible_y8i6dE/ansible_module_netscaler_servicegroup.py", line 548, in get_configured_monitor_bindings
    attribute_values_dict['servicegroupname'] = module.params['servicegroupname']
TypeError: 'str' object does not support item assignment

**Comment by chiradeep** [comment]
Can you show the playbook that causes the error?

**Comment by aelrayess** [comment]
---
- name: Create Load Balanced Server
  hosts: localhost
  gather_facts: False
  vars:
    ns_user: ansible
    ns_password: XXxxxx!!
    ns_ip: 192.168.121.4
    service_group_name: service-group-1
    web_servers:
      - ip: 192.168.122.24
        port: 80
        weight: 50
      - ip: 192.168.122.25
        port: 80
        weight: 50
    lb_vserver_ip: 192.168.122.30
    monitor_name: monitor_1

  tasks:
    - name: Set lb monitor
      netscaler_lb_monitor:
        nsip: "{{ ns_ip }}"
        nitro_user: "{{ ns_user }}"
        nitro_pass: "{{ ns_password }}"
        validate_certs: False
        state: present
        monitorname: "{{ monitor_name }}"
        type: HTTP-INLINE
        action: DOWN
        respcode: ['400']
        reverse: yes

    - name: Setup http service group
      netscaler_servicegroup:
        nsip: "{{ ns_ip }}"
        nitro_user: "{{ ns_user }}"
        nitro_pass: "{{ ns_password }}"
        validate_certs: False
        state: present
        servicegroupname: "{{ service_group_name }}" 
        servicetype: HTTP
        servicemembers: "{{ web_servers}}"
        monitorbindings:
          - monitorname: "{{ monitor_name }}"

    - name: Create load balancing vserver bound to servicegroup
      netscaler_lb_vserver:
        nsip: "{{ ns_ip }}"
        nitro_user: "{{ ns_user }}"
        nitro_pass: "{{ ns_password }}"
        validate_certs: False
        state: present
        name: lb_vserver_1
        servicetype: HTTP
        ipv46: "{{ lb_vserver_ip}}"
        port: 80
        servicegroupbindings:
          - servicegroupname: "{{ service_group_name }}"

**Comment by aelrayess** [comment]
I am trying it against netscaler vpx 12.0-41.16

**Comment by giorgos-nikolopoulos** [comment]
I could not reproduce the error.

I ran the playbook against the same NS version with you with both python2 and python3 but I did not see the error you mention.

The only error I got was a missing `weight` value from the monitorbindings entry.

Here is the playbook I ran.
```
---
- name: Create Load Balanced Server
  hosts: localhost
  gather_facts: False
  vars:
    ns_user: nsroot
    ns_password: nsroot
    ns_ip: 10.78.60.202
    service_group_name: service-group-1
    web_servers:
      - ip: 192.168.122.24
        port: 80
        weight: 50
      - ip: 192.168.122.25
        port: 80
        weight: 50
    lb_vserver_ip: 192.168.122.30
    monitor_name: monitor_1

  tasks:
  - name: Set lb monitor
    netscaler_lb_monitor:
      nsip: "{{ ns_ip }}"
      nitro_user: "{{ ns_user }}"
      nitro_pass: "{{ ns_password }}"
      validate_certs: False
      state: present
      monitorname: "{{ monitor_name }}"
      type: HTTP-INLINE
      action: DOWN
      respcode: ['400']
      reverse: yes

  - name: Setup http service group
    netscaler_servicegroup:
      nsip: "{{ ns_ip }}"
      nitro_user: "{{ ns_user }}"
      nitro_pass: "{{ ns_password }}"
      validate_certs: False
      state: present
      servicegroupname: "{{ service_group_name }}"
      servicetype: HTTP
      servicemembers: "{{ web_servers }}"
      monitorbindings:
      - monitorname: "{{ monitor_name }}"
        weight: 100

  - name: Create load balancing vserver bound to servicegroup
    netscaler_lb_vserver:
      nsip: "{{ ns_ip }}"
      nitro_user: "{{ ns_user }}"
      nitro_pass: "{{ ns_password }}"
      validate_certs: False
      state: present
      name: lb_vserver_1
      servicetype: HTTP
      ipv46: "{{ lb_vserver_ip }}"
      port: 80
      servicegroupbindings:
      - servicegroupname: "{{ service_group_name }}"
```

The only changes I made are the login credentials to the Netscaler node and I added the missing `weight` value.

Try to install the latest version of the modules from this repo and run the playbook again.

If you encounter an error please run the playbook with `-vvv` and record the output of the command to help us troubleshoot the issue.
