### ISSUE TITLE
Unable to parse "YES" or "NO" value in attribute in nitro_request

### ISSUE THREAD

**Issue by paulfirelordmu** [citrix/netscaler-ansible-modules#81]
**ISSUE**
Unable to parse "YES" or "NO" value in attribute in nitro_request. For instance, key "usip" in service. Ansible may change value into "true" or "false".

**ISSUE TYPE**
Bug Report

**ANSIBLE VERSION**
```
ansible 2.7.7
  config file = /Users/paulfirelord/Documents/ScriptConfig/Ansible/awx/ansible.cfg
  configured module search path = ['/Users/paulfirelord/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.2 (default, Jan 13 2019, 12:50:01) [Clang 10.0.0 (clang-1000.11.45.5)]
```

**STEPS TO REPRODUCE**
playbook
```
     vars:
       attributes_service:
       name: "xxxxx"
       port: "xxxxx"
       ip: "xxxxx"
       serviceType: HTTP
       usip: NO
       cip: enabled
       cipheader: X-Forwarded-For
     tasks:
    - name: Add Service
      delegate_to: localhost
      register: result
      netscaler_nitro_request:
        expected_nitro_errorcode: [0, 273]
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        operation: add
        resource: service
        attributes: "{{ attributes_service }}"
      ignore_errors: result.nitro_errorcode == 273
```

**ACTUAL RESULTS**
```
TASK [Add Service1] **********************************************************************************************************************************
fatal: [xxx -> localhost]: FAILED! => {"changed": false, "http_response_body": "{ \"errorcode\": 1097, \"message\": \"Invalid argument value [false]\", \"severity\": \"ERROR\" }", "http_response_data": {"cache-control": "no-store, no-cache, must-revalidate, post-check=0, pre-check=0", "connection": "close", "content-length": "87", "content-type": "application/json; charset=utf-8", "date": "Tue, 05 Mar 2019 16:53:27 GMT", "expires": "Thu, 19 Nov 1981 08:52:00 GMT", "msg": "HTTP Error 400: Bad Request", "pragma": "no-cache", "server": "Apache", "status": 400, "url": "http://xxxxxx/nitro/v1/config/service"}, "msg": "NITRO Failure", "nitro_errorcode": 1097, "nitro_message": "Invalid argument value [false]", "nitro_severity": "ERROR"}
```

**Comment by giorgos-nikolopoulos** [comment]
The type conversion of string value `"NO"` to `false` is and Ansible built in behavior.

You can override this behavior by using type coercion in the playbook to force the type of the `usip` argument to remain a string. 

That is define the value like so:  `usip: !!str "NO"`

I tested it on the same Ansible version as you have and it works.
Below is the full playbook source I used to verify the fix.
```
- hosts: citrix_adc
  gather_facts: False
  vars:
    attributes_service:
      name: test_service_1
      port: 80
      ip: 192.168.10.1
      serviceType: HTTP
      usip: !!str "NO"
      cip: enabled
      cipheader: X-Forwarded-For
  tasks:
    - name: Add Service
      delegate_to: localhost
      register: result
      netscaler_nitro_request:
        expected_nitro_errorcode: [0, 273]
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        operation: add
        resource: service
        attributes: "{{ attributes_service }}"
      ignore_errors: result.nitro_errorcode == 273
```

Let us know if this works out for you.
