### ISSUE TITLE
pfx example needed in doc

### ISSUE THREAD

**Issue by ActualReverend** [citrix/netscaler-ansible-modules#85]
It is a bit ambiguous how a pfx file can be imported, and I cannot seem to find any examples.  When a PFX file is used, is it used for the "certkey", or do I still have to export a public key for the certificate, then use the PFX for the certkey?  Or is it something else?

**Comment by giorgos-nikolopoulos** [comment]
I assume here that PFX refers to the PKCS#12 file format which acts as a container for certificates and keys.

So if you have a PEM certificate certificate.pem being the certificate file and key.pem the private key file you would create a certificate named certificate1 with the following task

```
    - name: Set ssl certificate key
      delegate_to: localhost
      citrix_adc_ssl_certkey:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        state: present

        certkey: certificate1
        cert: certificate.pem
        key: key.pem
        password: yes
        passplain: nosecret
        expirymonitor: enabled
        notificationperiod: 50
        inform: PEM
```
To create the same key and certificate to PFX format the following open ssl command would be run.

```
openssl pkcs12 -export -out certificate.pfx -inkey key.pem -in certificate.pem
```

Notice that the key and certificate are now both in the single `certificate.pfx` file.

So to create a certificate with this pfx file the following task would be run
```
---

- hosts: citrix_adc

  vars:
    max_clients: 5

  remote_user: root
  gather_facts: False

  tasks:
    - name: Set ssl certificate key
      delegate_to: localhost
      citrix_adc_ssl_certkey:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        state: present

        certkey: certificate1
        cert: certificate.pfx
        password: yes
        passplain: nosecret
        expirymonitor: enabled
        notificationperiod: 50
        inform: PFX

```

The difference from the previous task is that only the `cert` argument needs to be defined and also you have to change the `inform` argument to `PFX`.

I tested this on Citrix ADC 12.1 and it worked correctly.

You can find further information for SSL certificates on ADC on the following page [link](https://docs.citrix.com/en-us/citrix-adc/12-1/ssl/ssl-certificates.html)

@ActualReverend  Let us know if this works out for you.
