### ISSUE TITLE
Support for targeting partitions

### ISSUE THREAD

**Issue by brenwhyte** [citrix/netscaler-ansible-modules#91]
**SUMMARY**
One cannot target partitions on the Netscaler.
Only the default partition can be manipulated right now.

**ISSUE TYPE**
    _Feature Idea_
    Allow support for specifing the partition name/id as a var
    Much like this module
    https://github.com/networktocode/netscaler-ansible/blob/master/library/netscaler_server.py#L615-L624

**COMPONENT NAME**
citrix_adc_server.py

**ADDITIONAL INFORMATION**
This feature would allow users to target partitions on Netscalers. Many users like myself would have multiple partitions configured and the default partition is not used al all.

This "netscaler_server" module from networktocode has the right idea.
Be great if this was something that came out of the box.

https://github.com/networktocode/netscaler-ansible/blob/master/library/netscaler_server.py#L615-L624

**Comment by giorgos-nikolopoulos** [comment]
The way to address this issue at the moment is by using the citrix_adc_nitro_request module to login switch partition and then apply configuration to the partition.

This is showcased in the following playbook.

```
- hosts: citrix_adc
  gather_facts: no

  tasks:
    - name: Login
      delegate_to: localhost
      citrix_adc_nitro_request:
        nsip: "{{ nsip }}"
        operation: action
        action: login
        resource: login
        attributes:
          username: nsroot
          password: nsroot
      register: result

    - name: Save session id
      set_fact:
        sessionid: "{{ result.http_response_data.cookies.sessionid }}"

    - name: Switch partition
      delegate_to: localhost
      citrix_adc_nitro_request:
        nsip: "{{ nsip }}"
        nitro_auth_token: "{{ sessionid }}"
        operation: action
        action: switch
        resource: nspartition
        attributes:
          partitionname: george_test

    - name: Create server in partition
      delegate_to: localhost
      citrix_adc_nitro_request:
        nsip: "{{ nsip }}"
        nitro_auth_token: "{{ sessionid }}"
        operation: add
        resource: server
        attributes:
          name: george_test
          ipaddress: 12.33.22.55
``` 
Support for the `nitro_auth_token` attribute, which allows for switching partitions and applying configuration to them, is currently limitied to the citrix_adc_nitro_request module and the newer appfw modules.

We will need to add this feature to the older modules as well to facilitate this functionality.

We will be keeping track of this issue and address it on the first opportunity.
